services:
  - type: web
    name: ccenclave
    runtime: ruby
    buildCommand: bundle install && npm install && bin/bridgetown frontend:build
    startCommand: bin/bridgetown start
    envVars:
      - key: BRIDGETOWN_ENV
        value: production
      - key: BRIDGETOWN_PORT
        value: 10000
###########
# Uncomment and modify the following for database support, etc.
###########
#
#       - key: DATABASE_URL
#         fromDatabase:
#           name: ccenclave_proddb
#           property: connectionString
#       - fromGroup: ccenclave-prod-envs
# databases:
#   - name: ccenclave_proddb
#     plan: starter
#     databaseName: ccenclave_production
